# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def core_pods
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Bluejay
  pod 'SwiftLint'
end

def demo_pods
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Bluejay Demo

end

target 'Bluejay' do

  core_pods

end

target 'BluejayHeartSensorDemo' do

  demo_pods

end

target 'DittojayHeartSensorDemo' do

  demo_pods

end
