# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BluejayDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BluejayDemo
  pod 'Bluejay', :git => 'https://github.com/steamclock/bluejay.git', :branch => 'master'
  
end
